#pragma once


#define PREDPROCESSOR_TO_STRING(x) PREDPROCESSOR_TO_STRING_INNER(x)
#define PREDPROCESSOR_TO_STRING_INNER(x) #x


#define PREDPROCESSOR_JOIN(x, y) PREDPROCESSOR_JOIN_INNER(x, y)
#define PREDPROCESSOR_JOIN_INNER(x, y) x##y




#define DE_SOURCE_LOCATION TEXT(__FILE__ "(" PREPROCESSOR_TO_STRING(__LINE__) ")")



#define COMPILED_PLATFORM_HEADER(Suffix) PREDPROCESSOR_TO_STRING(PREDPROCESSOR_JOIN(PLATFORM_HEADER_NAME/PLATFORM_HEADER_NAME, Suffix))