#pragma once


#define ENGINE_MAJOR_VERSION	0
#define ENGINE_MINOR_VERSION	1
#define ENGINE_PATCH_VERSION	0


#define VERSION_TEXT(x) TEXT(x)
#define VERSION_STRINGIFY(x) VERSION_TEXT(#x)



#define DARK_COMPANY_NAME	"Dark, Inc"
#define DARK_COPYRIGHT_STRING	"Copyright Dark, 2020. All Rights Reserved"
#define DARK_PRODUCT_NAME	"Dark Engine"
#define DARK_PRODUCT_IDENTIFIER	"DarkEngine"


#define ENGINE_VERSION_STRING	VERSION_STRINGIFY(ENGINE_MAJOR_VERSION) \
								VERSION_TEXT(".") \
								VERSION_STRINGIFY(ENGINE_MINOR_VERSION) \
								VERSION_TEXT(".") \
								VERSION_STRINGIFY(ENGINE_PATCH_VERSION)

