name: CI

on:
  push:
    branches: [Release]
  pull_request:
    branches: [Release]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
   # - uses: lukka/run-vcpkg@v11 # Always specify the specific _version_ of the
   #    name: Setup anew (or from cache) vcpkg (and does not build any package)
    - uses: microsoft/setup-msbuild@v2
      name: setup-msbuild
      with:
        msbuild-architecture: x64 # optional, default is x86
  
    - uses: TheMrMilchmann/setup-msvc-dev@v3.0.0
      name: Setup MSVC Developer Command Prompt
      with:
        # The target architecture
        arch: x64
        # The path to the Visual Studio installation
        # Windows SDK to use
        sdk: 10.0.22621.0 # optional
        # Use Visual Studio libraries with Spectre mitigations
        spectre: false # optional
        # VC++ compiler toolset version
        toolset: 14.39.33519 # optional
        # Build for Universal Windows Platform
        uwp: false
        # The environment variable to store the path to vcvarsall.bat in
        #export-path-to-vcvarsall: # optional
        # The environment variable to store the path to the Visual Studio installation in
        #export-path-to-vs: # optional
          


      
    - uses: lukka/get-cmake@v3.29.3
      name: get-cmake
      #with:
        # Optional CMake version, expressed with the semantic version syntax, e.g. '~3.25.0' for the most recent 3.25.x, `Ë†3.25.0` for the most recent 3.x version, or a specific version `3.25.2'. Or `latest` or `latestrc` for the latest stable or release candidate version. If not specified the `latest` is installed.
       # cmakeVersion: # optional
        # Optional Ninja version, same syntax as `cmakeVersion` input. If not specified, `latest` is installed
       # ninjaVersion: # optional
        # Optional argument indicating whether to use the cloud based storage of the GitHub cache. Suited for the GitHub-hosted runners.
        #useCloudCache: # optional, default is true
        # Optional argument indicating whether to use the local cache on the GitHub runner file system. Suited for the self-hosted GitHub runners.
        #useLocalCache: # optional
    - uses: lukka/run-cmake@v10.7
      name: run-cmake
      with:
      # Path to CMakeLists.txt.
        cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt # optional, default is ${{ github.workspace }}/CMakeLists.txt
        configurePreset: 'ninja'
        buildPreset: 'ninja'
        
      
      
